-- Insert sample data for diseases
INSERT INTO diseases (name, description, symptoms, dietary_guidelines) VALUES
('Diabetes', 'A metabolic disorder characterized by high blood sugar levels.', 'Frequent urination, excessive thirst, fatigue', 'Low glycemic index foods, balanced carbs, regular meals'),
('Hypertension', 'High blood pressure that can lead to heart disease.', 'Headaches, dizziness, chest pain', 'Low sodium diet, DASH diet, potassium-rich foods'),
('Obesity', 'Excess body fat that may impair health.', 'Shortness of breath, joint pain, fatigue', 'Calorie deficit, high protein, whole foods'),
('Heart Disease', 'Conditions affecting the heart and blood vessels.', 'Chest pain, shortness of breath, fatigue', 'Heart-healthy fats, omega-3s, Mediterranean diet'),
('Anemia', 'A condition in which you lack enough healthy red blood cells.', 'Fatigue, weakness, pale skin', 'Iron-rich foods, vitamin C for absorption'),
('Arthritis', 'Inflammation of the joints causing pain and stiffness.', 'Joint pain, swelling, reduced mobility', 'Anti-inflammatory foods, omega-3s, weight management'),
('Asthma', 'Chronic respiratory condition with airway inflammation.', 'Wheezing, coughing, shortness of breath', 'Anti-inflammatory diet, vitamin D, magnesium'),
('Cancer', 'Uncontrolled cell growth leading to tumors.', 'Unexplained weight loss, fatigue, pain', 'Plant-based diet, antioxidants, whole foods'),
('Chronic Kidney Disease', 'Gradual loss of kidney function.', 'Fatigue, swelling, changes in urination', 'Low sodium, low phosphorus, adequate protein'),
('Depression', 'Mood disorder with persistent sadness.', 'Persistent sadness, loss of interest, fatigue', 'Omega-3s, B vitamins, complex carbs'),
('Gout', 'Form of arthritis with uric acid crystal deposits.', 'Sudden joint pain, swelling, redness', 'Low purine diet, hydration, vitamin C'),
('Irritable Bowel Syndrome', 'Digestive disorder affecting bowel habits.', 'Abdominal pain, bloating, irregular bowel movements', 'High fiber, probiotics, low FODMAP'),
('Migraine', 'Severe headache often with nausea and sensitivity.', 'Throbbing pain, nausea, light sensitivity', 'Magnesium, riboflavin, avoid triggers'),
('Osteoporosis', 'Bone density loss leading to fractures.', 'Bone pain, height loss, fractures', 'Calcium-rich foods, vitamin D, weight-bearing exercise'),
('Thyroid Disorders', 'Imbalances in thyroid hormone production.', 'Fatigue, weight changes, mood swings', 'Iodine-rich foods, selenium, balanced nutrition'),
('Alzheimer''s Disease', 'Progressive neurodegenerative disorder.', 'Memory loss, confusion, behavioral changes', 'Mediterranean diet, antioxidants, omega-3s'),
('Parkinson''s Disease', 'Movement disorder affecting motor functions.', 'Tremors, stiffness, balance issues', 'High protein, antioxidants, balanced diet'),
('Multiple Sclerosis', 'Autoimmune disease affecting the nervous system.', 'Fatigue, numbness, coordination problems', 'Anti-inflammatory diet, vitamin D, omega-3s'),
('Rheumatoid Arthritis', 'Autoimmune arthritis affecting multiple joints.', 'Joint pain, swelling, morning stiffness', 'Anti-inflammatory foods, omega-3s, antioxidants'),
('Celiac Disease', 'Autoimmune disorder triggered by gluten.', 'Digestive issues, fatigue, nutrient deficiencies', 'Gluten-free diet, nutrient-dense foods'),
('Crohn''s Disease', 'Chronic inflammatory bowel disease.', 'Abdominal pain, diarrhea, weight loss', 'Low residue diet, probiotics, nutrient support'),
('Ulcerative Colitis', 'Inflammatory bowel disease affecting colon.', 'Bloody diarrhea, abdominal pain, fatigue', 'Low fiber during flares, probiotics, hydration'),
('Gallstones', 'Hardened deposits in the gallbladder.', 'Abdominal pain, nausea, jaundice', 'Low fat diet, gradual weight loss, fiber'),
('Hepatitis', 'Inflammation of the liver.', 'Fatigue, jaundice, abdominal pain', 'Liver-supportive diet, antioxidants, hydration'),
('Pancreatitis', 'Inflammation of the pancreas.', 'Severe abdominal pain, nausea, fever', 'Low fat diet, small frequent meals, hydration'),
('Peptic Ulcer', 'Sores in the stomach lining.', 'Burning stomach pain, bloating, nausea', 'Avoid irritants, probiotics, balanced meals'),
('GERD', 'Acid reflux disease.', 'Heartburn, regurgitation, chest pain', 'Avoid trigger foods, small meals, elevation'),
('Diverticulitis', 'Inflammation of diverticula in the colon.', 'Abdominal pain, fever, constipation', 'High fiber diet, hydration, probiotics'),
('Hemorrhoids', 'Swollen veins in the rectum.', 'Pain, itching, bleeding', 'High fiber diet, hydration, avoid straining'),
('Kidney Stones', 'Hard mineral deposits in kidneys.', 'Severe pain, blood in urine, nausea', 'Low oxalate, high calcium, hydration'),
('Bladder Infection', 'Urinary tract infection affecting bladder.', 'Frequent urination, burning, pelvic pain', 'Cranberry, hydration, probiotics'),
('Prostate Issues', 'Conditions affecting prostate gland.', 'Urinary problems, pain, erectile issues', 'Plant-based diet, lycopene, zinc'),
('Menopause', 'Natural decline in female hormones.', 'Hot flashes, mood changes, sleep issues', 'Calcium, vitamin D, phytoestrogens'),
('PCOS', 'Hormonal disorder in women.', 'Irregular periods, weight gain, acne', 'Low GI diet, anti-inflammatory foods, weight management'),
('Endometriosis', 'Tissue growth outside uterus.', 'Pelvic pain, heavy periods, infertility', 'Anti-inflammatory diet, omega-3s, iron-rich foods'),
('Fibromyalgia', 'Chronic pain and fatigue syndrome.', 'Widespread pain, fatigue, sleep issues', 'Anti-inflammatory diet, magnesium, balanced nutrition'),
('Chronic Fatigue Syndrome', 'Long-term fatigue and other symptoms.', 'Severe fatigue, pain, cognitive issues', 'Balanced nutrition, B vitamins, antioxidants'),
('Lupus', 'Autoimmune disease affecting multiple systems.', 'Fatigue, joint pain, skin rashes', 'Anti-inflammatory diet, omega-3s, antioxidants'),
('Scleroderma', 'Autoimmune disease causing skin thickening.', 'Skin changes, joint pain, digestive issues', 'Anti-inflammatory diet, hydration, nutrient support'),
('Sarcoidosis', 'Inflammatory disease with granulomas.', 'Fatigue, shortness of breath, skin lesions', 'Anti-inflammatory diet, vitamin D, calcium'),
('Vasculitis', 'Inflammation of blood vessels.', 'Fatigue, fever, organ damage', 'Anti-inflammatory diet, balanced nutrition'),
('Ankylosing Spondylitis', 'Inflammatory arthritis of the spine.', 'Back pain, stiffness, fatigue', 'Anti-inflammatory diet, omega-3s, calcium'),
('Psoriatic Arthritis', 'Arthritis associated with psoriasis.', 'Joint pain, skin plaques, fatigue', 'Anti-inflammatory diet, omega-3s, vitamin D'),
('Gouty Arthritis', 'Arthritis from uric acid crystals.', 'Joint pain, swelling, redness', 'Low purine diet, hydration, vitamin C'),
('Osteoarthritis', 'Degenerative joint disease.', 'Joint pain, stiffness, reduced mobility', 'Glucosamine, omega-3s, weight management'),
('Bursitis', 'Inflammation of bursae around joints.', 'Joint pain, swelling, limited movement', 'Anti-inflammatory diet, rest, ice'),
('Tendonitis', 'Inflammation of tendons.', 'Pain, swelling, reduced function', 'Anti-inflammatory diet, rest, ice'),
('Carpal Tunnel Syndrome', 'Nerve compression in wrist.', 'Hand pain, numbness, weakness', 'Anti-inflammatory diet, vitamin B6, ergonomics'),
('Sciatica', 'Pain from sciatic nerve compression.', 'Leg pain, numbness, weakness', 'Anti-inflammatory diet, posture, exercise'),
('Herniated Disc', 'Disc protrusion pressing on nerves.', 'Back pain, leg pain, numbness', 'Anti-inflammatory diet, posture, core strength'),
('Scoliosis', 'Spinal curvature.', 'Back pain, uneven shoulders, fatigue', 'Calcium, vitamin D, posture exercises'),
('Kyphosis', 'Excessive spinal curvature.', 'Back pain, poor posture, breathing issues', 'Calcium, vitamin D, posture correction'),
('Lordosis', 'Excessive inward spinal curve.', 'Back pain, posture issues, fatigue', 'Core strengthening, posture correction'),
('Spinal Stenosis', 'Narrowing of spinal canal.', 'Back pain, leg pain, numbness', 'Anti-inflammatory diet, posture, gentle exercise'),
('Whiplash', 'Neck injury from sudden movement.', 'Neck pain, stiffness, headaches', 'Anti-inflammatory diet, rest, gentle stretching'),
('Concussion', 'Brain injury from head trauma.', 'Headache, confusion, dizziness', 'Rest, hydration, nutrient support'),
('Epilepsy', 'Neurological disorder with seizures.', 'Seizures, confusion, fatigue', 'Ketogenic diet, antioxidants, balanced nutrition'),
('Stroke', 'Brain damage from interrupted blood flow.', 'Weakness, speech issues, cognitive changes', 'Mediterranean diet, omega-3s, antioxidants'),
('Transient Ischemic Attack', 'Mini-stroke with temporary symptoms.', 'Temporary weakness, speech issues', 'Same as stroke prevention diet'),
('Aneurysm', 'Bulge in blood vessel wall.', 'Headache, vision changes, pain', 'Blood pressure control diet, omega-3s'),
('Deep Vein Thrombosis', 'Blood clot in deep vein.', 'Leg pain, swelling, redness', 'Hydration, vitamin K moderation, exercise'),
('Pulmonary Embolism', 'Blood clot in lung artery.', 'Shortness of breath, chest pain, coughing', 'Anticoagulant-friendly diet, hydration'),
('Varicose Veins', 'Enlarged, twisted veins.', 'Leg pain, swelling, visible veins', 'High fiber, flavonoids, exercise'),
('Peripheral Artery Disease', 'Narrowed arteries reducing blood flow.', 'Leg pain, cramping, fatigue', 'Mediterranean diet, omega-3s, exercise'),
('Aortic Aneurysm', 'Bulge in aorta.', 'Back pain, abdominal pain, pulsatile mass', 'Blood pressure control, omega-3s'),
('Coronary Artery Disease', 'Plaque buildup in heart arteries.', 'Chest pain, shortness of breath, fatigue', 'Heart-healthy diet, omega-3s, fiber'),
('Congenital Heart Defects', 'Heart abnormalities present at birth.', 'Fatigue, shortness of breath, cyanosis', 'Heart-healthy diet, balanced nutrition'),
('Cardiomyopathy', 'Disease of heart muscle.', 'Fatigue, shortness of breath, swelling', 'Low sodium, heart-healthy fats'),
('Heart Failure', 'Heart unable to pump effectively.', 'Fatigue, shortness of breath, swelling', 'Low sodium, fluid restriction, balanced diet'),
('Arrhythmia', 'Irregular heartbeat.', 'Palpitations, dizziness, fatigue', 'Magnesium, potassium, omega-3s'),
('Atrial Fibrillation', 'Irregular and often rapid heartbeat.', 'Palpitations, fatigue, shortness of breath', 'Anticoagulant-friendly diet, omega-3s'),
('Bradycardia', 'Slow heart rate.', 'Fatigue, dizziness, fainting', 'Electrolyte balance, thyroid support'),
('Tachycardia', 'Fast heart rate.', 'Palpitations, dizziness, fatigue', 'Caffeine moderation, stress management'),
('Mitral Valve Prolapse', 'Mitral valve doesn''t close properly.', 'Palpitations, chest pain, fatigue', 'Magnesium, calcium, balanced diet'),
('Aortic Stenosis', 'Narrowing of aortic valve.', 'Chest pain, fatigue, shortness of breath', 'Heart-healthy diet, vitamin K moderation'),
('Pneumonia', 'Lung infection causing inflammation.', 'Cough, fever, shortness of breath', 'Hydration, nutrient support, rest'),
('Bronchitis', 'Inflammation of bronchial tubes.', 'Cough, mucus, fatigue', 'Hydration, honey, steam inhalation'),
('Emphysema', 'Lung damage from smoking/toxins.', 'Shortness of breath, cough, fatigue', 'Antioxidants, omega-3s, lung-supportive foods'),
('Chronic Bronchitis', 'Long-term bronchial inflammation.', 'Chronic cough, mucus, fatigue', 'Anti-inflammatory diet, hydration'),
('Cystic Fibrosis', 'Genetic lung and digestive disorder.', 'Cough, lung infections, digestive issues', 'High calorie, high fat, pancreatic enzymes'),
('Pulmonary Fibrosis', 'Scarring of lung tissue.', 'Shortness of breath, cough, fatigue', 'Antioxidants, anti-inflammatory foods'),
('Sleep Apnea', 'Breathing pauses during sleep.', 'Daytime fatigue, snoring, headaches', 'Weight management, avoid sedatives'),
('Insomnia', 'Difficulty falling or staying asleep.', 'Fatigue, irritability, concentration issues', 'Magnesium, tryptophan, sleep hygiene'),
('Narcolepsy', 'Sudden sleep attacks.', 'Excessive daytime sleepiness, cataplexy', 'Balanced diet, regular sleep schedule'),
('Restless Legs Syndrome', 'Urge to move legs, usually at night.', 'Leg discomfort, sleep disruption', 'Iron, magnesium, folate'),
('Sleepwalking', 'Performing activities while asleep.', 'Unconscious activities, fatigue', 'Regular sleep schedule, stress reduction'),
('Night Terrors', 'Sudden awakenings with terror.', 'Screaming, confusion, amnesia', 'Regular sleep, stress management'),
('Acne', 'Skin condition with pimples and cysts.', 'Pimples, blackheads, scarring', 'Low glycemic diet, zinc, omega-3s'),
('Eczema', 'Chronic skin inflammation.', 'Itchy, red, dry skin', 'Anti-inflammatory diet, probiotics, hydration'),
('Psoriasis', 'Autoimmune skin disorder.', 'Red, scaly patches, itching', 'Anti-inflammatory diet, vitamin D, omega-3s'),
('Rosacea', 'Facial redness and visible blood vessels.', 'Facial redness, bumps, eye irritation', 'Avoid triggers, anti-inflammatory diet'),
('Dermatitis', 'Skin inflammation from various causes.', 'Redness, itching, rash', 'Moisturizing, anti-inflammatory foods'),
('Vitiligo', 'Loss of skin pigmentation.', 'White patches on skin', 'Antioxidants, vitamin B12, copper'),
('Melanoma', 'Aggressive form of skin cancer.', 'Irregular mole, changes in skin', 'Antioxidant-rich diet, sun protection'),
('Basal Cell Carcinoma', 'Most common skin cancer.', 'Pearly bump, open sore', 'Antioxidants, vitamin D'),
('Squamous Cell Carcinoma', 'Skin cancer from squamous cells.', 'Scaly red patch, open sore', 'Antioxidants, vitamin D'),
('Seborrheic Dermatitis', 'Skin condition causing dandruff.', 'Greasy, scaly patches', 'Anti-inflammatory diet, zinc'),
('Hives', 'Raised, itchy welts on skin.', 'Itchy welts, swelling', 'Antihistamine diet, identify triggers'),
('Cellulitis', 'Bacterial skin infection.', 'Red, swollen, painful skin', 'Antibiotics, immune support, hydration'),
('Impetigo', 'Highly contagious skin infection.', 'Red sores, honey-crusted lesions', 'Hygiene, immune support'),
('Ringworm', 'Fungal skin infection.', 'Itchy, circular rash', 'Antifungal diet, hygiene'),
('Athlete''s Foot', 'Fungal infection of feet.', 'Itchy, scaly skin between toes', 'Antifungal foods, keep feet dry'),
('Jock Itch', 'Fungal infection in groin area.', 'Itchy, red rash', 'Antifungal diet, hygiene'),
('Candidiasis', 'Yeast infection.', 'Itching, redness, discharge', 'Low sugar diet, probiotics'),
('Scabies', 'Parasitic skin infestation.', 'Intense itching, burrows', 'Hygiene, treatment compliance'),
('Lice', 'Parasitic insects on scalp/body.', 'Itching, visible lice/eggs', 'Hygiene, treatment'),
('Bedbugs', 'Parasitic insects that bite at night.', 'Itchy bites, welts', 'Hygiene, pest control'),
('Allergies', 'Immune system overreaction.', 'Sneezing, itching, swelling', 'Anti-inflammatory diet, local foods'),
('Food Allergies', 'Adverse immune reaction to foods.', 'Hives, swelling, anaphylaxis', 'Avoid allergens, balanced diet'),
('Environmental Allergies', 'Reaction to environmental triggers.', 'Sneezing, itchy eyes, congestion', 'Local honey, anti-inflammatory foods'),
('Drug Allergies', 'Reaction to medications.', 'Rash, swelling, anaphylaxis', 'Avoid offending drugs, alternatives'),
('Latex Allergy', 'Reaction to latex proteins.', 'Rash, itching, anaphylaxis', 'Latex-free products, alternatives'),
('Insect Sting Allergies', 'Reaction to insect venom.', 'Swelling, pain, anaphylaxis', 'EpiPen, avoid stings'),
('Pet Allergies', 'Reaction to pet dander.', 'Sneezing, itchy eyes, congestion', 'Air filtration, hypoallergenic pets'),
('Dust Mite Allergies', 'Reaction to dust mite feces.', 'Sneezing, congestion, itchy eyes', 'Dust control, air filtration'),
('Mold Allergies', 'Reaction to mold spores.', 'Sneezing, congestion, fatigue', 'Humidity control, air filtration'),
('Pollen Allergies', 'Reaction to plant pollen.', 'Sneezing, itchy eyes, congestion', 'Local pollen avoidance, antihistamines'),
('Egg Allergy', 'Immune reaction to egg proteins.', 'Hives, swelling, digestive issues', 'Egg-free diet, alternatives'),
('Milk Allergy', 'Reaction to milk proteins.', 'Hives, swelling, digestive issues', 'Dairy-free diet, calcium alternatives'),
('Peanut Allergy', 'Severe reaction to peanuts.', 'Anaphylaxis, swelling, rash', 'Peanut-free diet, EpiPen'),
('Tree Nut Allergy', 'Reaction to tree nuts.', 'Anaphylaxis, swelling, rash', 'Nut-free diet, alternatives'),
('Shellfish Allergy', 'Reaction to shellfish.', 'Anaphylaxis, swelling, rash', 'Shellfish-free diet, alternatives'),
('Fish Allergy', 'Reaction to fish proteins.', 'Anaphylaxis, swelling, rash', 'Fish-free diet, alternatives'),
('Soy Allergy', 'Reaction to soy proteins.', 'Hives, swelling, digestive issues', 'Soy-free diet, alternatives'),
('Wheat Allergy', 'Reaction to wheat proteins.', 'Hives, swelling, digestive issues', 'Gluten-free diet, alternatives');

-- Insert sample data for recipes (250 recipes associated with diseases)
INSERT INTO recipes (name, ingredients, preparation_steps, calories, protein, carbs, fats, allergens, meal_type, cuisine_type, is_vegetarian, disease_id) VALUES
('Low-Glycemic Vegetable Stir-Fry', '["broccoli", "carrots", "bell peppers", "zucchini", "low-sodium soy sauce", "ginger", "garlic"]', '["Chop all vegetables into bite-sized pieces", "Heat oil in a wok or large pan", "Add ginger and garlic, stir for 1 minute", "Add vegetables and stir-fry for 5-7 minutes", "Add soy sauce and cook for another 2 minutes", "Serve hot"]', 180, 6, 25, 8, '["soy"]', 'Dinner', 'Asian', true, 1),
('Grilled Chicken with Quinoa', '["chicken breast", "quinoa", "broccoli", "olive oil", "lemon", "herbs"]', '["Cook quinoa according to package", "Season chicken with herbs and olive oil", "Grill chicken for 6-8 minutes per side", "Steam broccoli", "Serve chicken with quinoa and broccoli, drizzle with lemon"]', 420, 35, 35, 15, '[]', 'Dinner', 'Mediterranean', false, 1),
('Berry Oatmeal Bowl', '["oats", "mixed berries", "almond milk", "chia seeds", "cinnamon"]', '["Cook oats with almond milk", "Top with berries and chia seeds", "Sprinkle cinnamon", "Let sit for 5 minutes to thicken"]', 280, 8, 45, 9, '["nuts"]', 'Breakfast', 'American', true, 1),
('Turkey Lettuce Wraps', '["ground turkey", "lettuce leaves", "cucumber", "carrots", "hoisin sauce", "ginger"]', '["Cook ground turkey with ginger", "Chop vegetables", "Fill lettuce leaves with turkey and veggies", "Drizzle with hoisin sauce"]', 220, 25, 12, 10, '[]', 'Lunch', 'Asian', false, 1),
('Baked Salmon with Asparagus', '["salmon fillet", "asparagus", "olive oil", "lemon", "dill"]', '["Preheat oven to 400°F", "Place salmon and asparagus on baking sheet", "Drizzle with olive oil and lemon", "Bake for 15-20 minutes", "Sprinkle with dill"]', 380, 32, 8, 25, '["fish"]', 'Dinner', 'Mediterranean', false, 1),
('Greek Yogurt Parfait', '["greek yogurt", "strawberries", "blueberries", "granola", "honey"]', '["Layer yogurt in a glass", "Add berries", "Top with granola", "Drizzle honey"]', 250, 20, 30, 6, '[]', 'Breakfast', 'Greek', true, 1),
('Spinach and Mushroom Omelette', '["eggs", "spinach", "mushrooms", "onion", "olive oil"]', '["Sauté mushrooms and onion", "Add spinach until wilted", "Pour beaten eggs over veggies", "Cook until set, fold over"]', 280, 18, 6, 20, '["eggs"]', 'Breakfast', 'American', true, 1),
('Lentil Soup', '["lentils", "carrots", "celery", "onion", "vegetable broth", "tomatoes", "spices"]', '["Sauté vegetables", "Add lentils and broth", "Simmer for 30 minutes", "Blend partially for texture", "Season to taste"]', 220, 14, 35, 3, '[]', 'Lunch', 'Mediterranean', true, 1),
('Grilled Vegetable Skewers', '["zucchini", "bell peppers", "onion", "cherry tomatoes", "olive oil", "herbs"]', '["Cut vegetables into chunks", "Thread onto skewers", "Brush with olive oil and herbs", "Grill for 10-15 minutes"]', 150, 4, 18, 8, '[]', 'Dinner', 'Mediterranean', true, 1),
('Chicken Vegetable Soup', '["chicken breast", "carrots", "celery", "onion", "broth", "spinach"]', '["Cook chicken in broth", "Add chopped vegetables", "Simmer until tender", "Shred chicken and return to pot", "Add spinach at end"]', 180, 22, 12, 5, '[]', 'Lunch', 'American', false, 1),
('Banana Almond Smoothie', '["banana", "almond milk", "almond butter", "spinach", "protein powder"]', '["Blend all ingredients", "Add ice if desired", "Blend until smooth"]', 320, 15, 35, 15, '["nuts"]', 'Breakfast', 'American', true, 1),
('Tuna Salad Wraps', '["canned tuna", "celery", "onion", "greek yogurt", "whole wheat wraps", "lettuce"]', '["Mix tuna with veggies and yogurt", "Spread on wraps", "Add lettuce", "Roll up tightly"]', 280, 28, 25, 8, '["fish", "wheat"]', 'Lunch', 'American', false, 1),
('Sweet Potato Hash', '["sweet potatoes", "onion", "bell peppers", "eggs", "olive oil"]', '["Dice sweet potatoes and cook", "Sauté onion and peppers", "Mix with potatoes", "Top with fried eggs"]', 350, 12, 40, 16, '["eggs"]', 'Breakfast', 'American', true, 1),
('Mediterranean Chickpea Salad', '["chickpeas", "cucumber", "tomatoes", "feta", "olives", "olive oil", "lemon"]', '["Drain and rinse chickpeas", "Chop vegetables", "Mix all ingredients", "Dress with oil and lemon"]', 320, 12, 35, 15, '[]', 'Lunch', 'Mediterranean', true, 1),
('Herb-Crusted Fish', '["white fish fillet", "herbs", "lemon", "olive oil", "quinoa"]', '["Mix herbs with oil", "Coat fish with mixture", "Bake at 375°F for 15 minutes", "Serve with cooked quinoa"]', 340, 30, 25, 14, '["fish"]', 'Dinner', 'Mediterranean', false, 1),
('Apple Cinnamon Oatmeal', '["oats", "apple", "cinnamon", "almond milk", "walnuts"]', '["Cook oats with milk", "Add diced apple and cinnamon", "Top with walnuts"]', 290, 8, 45, 10, '["nuts"]', 'Breakfast', 'American', true, 1),
('Turkey Stir-Fry', '["ground turkey", "broccoli", "carrots", "snow peas", "low-sodium soy sauce"]', '["Cook turkey", "Add vegetables", "Stir-fry until tender", "Add soy sauce"]', 260, 28, 15, 10, '["soy"]', 'Dinner', 'Asian', false, 1),
('Cucumber Tomato Salad', '["cucumber", "tomatoes", "red onion", "feta", "olive oil", "vinegar"]', '["Slice vegetables", "Crumble feta", "Mix with oil and vinegar"]', 120, 4, 12, 8, '[]', 'Lunch', 'Mediterranean', true, 1),
('Baked Chicken Breast', '["chicken breast", "herbs", "lemon", "olive oil", "green beans"]', '["Season chicken", "Bake at 375°F for 25 minutes", "Steam green beans", "Serve together"]', 280, 35, 8, 12, '[]', 'Dinner', 'American', false, 1),
('Berry Protein Smoothie', '["mixed berries", "greek yogurt", "protein powder", "spinach", "almond milk"]', '["Blend all ingredients", "Add ice for thickness"]', 280, 25, 25, 8, '[]', 'Breakfast', 'American', true, 1),
('Vegetable Curry', '["mixed vegetables", "coconut milk", "curry powder", "rice", "cilantro"]', '["Sauté vegetables", "Add curry and coconut milk", "Simmer 15 minutes", "Serve over rice"]', 320, 8, 45, 12, '[]', 'Dinner', 'Indian', true, 1),
('Egg White Frittata', '["egg whites", "spinach", "tomatoes", "onion", "feta"]', '["Sauté vegetables", "Pour egg whites over", "Top with feta", "Bake until set"]', 180, 18, 8, 8, '["eggs", "dairy"]', 'Breakfast', true, 1),
('Shrimp and Vegetable Stir-Fry', '["shrimp", "broccoli", "carrots", "bell peppers", "low-sodium soy sauce"]', '["Cook shrimp", "Add vegetables", "Stir-fry quickly", "Add soy sauce"]', 240, 28, 15, 8, '["shellfish", "soy"]', 'Dinner', 'Asian', false, 1),
('Quinoa Salad', '["quinoa", "cucumber", "cherry tomatoes", "feta", "olive oil", "lemon"]', '["Cook quinoa", "Chop vegetables", "Mix all ingredients"]', 350, 12, 40, 16, '[]', 'Lunch', 'Mediterranean', true, 1),
('Turkey Meatballs', '["ground turkey", "oats", "onion", "egg", "tomato sauce"]', '["Mix ingredients", "Form meatballs", "Bake or cook in sauce", "Serve with vegetables"]', 280, 30, 20, 12, '["eggs"]', 'Dinner', 'Italian', false, 1),
('Avocado Toast', '["whole grain bread", "avocado", "tomato", "olive oil", "salt"]', '["Toast bread", "Mash avocado on top", "Add tomato slices", "Drizzle oil"]', 280, 6, 30, 16, '["wheat"]', 'Breakfast', 'American', true, 1),
('Lentil Stew', '["lentils", "carrots", "celery", "onion", "vegetable broth", "spinach"]', '["Sauté vegetables", "Add lentils and broth", "Simmer 25 minutes", "Add spinach"]', 240, 14, 40, 4, '[]', 'Dinner', 'Mediterranean', true, 1),
('Grilled Fish Tacos', '["white fish", "corn tortillas", "cabbage", "lime", "cilantro"]', '["Grill seasoned fish", "Warm tortillas", "Fill with fish and cabbage", "Squeeze lime"]', 260, 25, 25, 8, '["fish"]', 'Mexican', false, 1),
('Vegetable Soup', '["mixed vegetables", "vegetable broth", "herbs", "olive oil"]', '["Sauté vegetables", "Add broth and herbs", "Simmer until tender"]', 120, 4, 20, 4, '[]', 'Lunch', 'American', true, 1),
('Chicken Caesar Salad', '["chicken breast", "romaine", "parmesan", "croutons", "caesar dressing"]', '["Grill chicken", "Chop romaine", "Toss with dressing", "Top with chicken and cheese"]', 380, 35, 15, 22, '["dairy", "wheat"]', 'Lunch', 'American', false, 1),
('Fruit Salad', '["mixed fruits", "mint", "lime juice", "honey"]', '["Chop fruits", "Mix with lime and honey", "Garnish with mint"]', 120, 2, 30, 1, '[]', 'Snack', 'American', true, 1),
('Beef Stir-Fry', '["lean beef", "broccoli", "carrots", "low-sodium soy sauce", "ginger"]', '["Slice beef thinly", "Stir-fry beef", "Add vegetables", "Season with soy and ginger"]', 320, 32, 15, 16, '["soy"]', 'Dinner', 'Asian', false, 1),
('Cottage Cheese Bowl', '["cottage cheese", "pineapple", "walnuts", "cinnamon"]', '["Mix cottage cheese with pineapple", "Top with walnuts", "Sprinkle cinnamon"]', 280, 25, 20, 12, '["dairy", "nuts"]', 'Breakfast', 'American', true, 1),
('Tomato Basil Soup', '["tomatoes", "basil", "onion", "vegetable broth", "olive oil"]', '["Sauté onion", "Add tomatoes and broth", "Simmer 20 minutes", "Blend and add basil"]', 140, 4, 18, 6, '[]', 'Lunch', 'Italian', true, 1),
('Salmon Salad', '["canned salmon", "celery", "onion", "greek yogurt", "lettuce"]', '["Mix salmon with veggies", "Add yogurt", "Serve over lettuce"]', 280, 28, 10, 14, '["fish"]', 'Lunch', 'American', false, 1),
('Vegetable Lasagna', '["lasagna noodles", "ricotta", "spinach", "zucchini", "tomato sauce"]', '["Cook noodles", "Layer with cheese and veggies", "Bake at 375°F for 30 minutes"]', 320, 16, 40, 12, '["wheat", "dairy"]', 'Dinner', 'Italian', true, 1),
('Turkey Burger', '["ground turkey", "onion", "lettuce", "tomato", "whole wheat bun"]', '["Mix turkey with onion", "Form patties", "Grill burgers", "Serve on bun with veggies"]', 280, 28, 25, 10, '["wheat"]', 'Lunch', 'American', false, 1),
